### ISSUE TITLE
Switch to uv projects

### ISSUE THREAD

**Issue by stefanofusai** [stefanofusai/drf-multi-serializers#46]
**.pre-commit-config.yaml**
- [x] Replace `skip: - pip-compile` with `skip: - uv-lock`
- [x] Remove `file-contents-sorter` on `.requirements/*` / `requirements.in`
- [x] Replace `pip-compile` hook with `uv-lock`
- [x] Bump uv to `0.5.6`

**dependabot.yml**
- [x] Change `directory: /.requirements` to `directory: /`

**README.md**
- [x] Add introduction section:
```md
This package uses [uv](https://docs.astral.sh/uv/) for project management. To get started, ensure that **uv** is installed on your machine and updated to the `0.5.6` version. Detailed installation instructions for **uv** can be found [here](https://docs.astral.sh/uv/getting-started/installation/).
```
- [x] Add relevant sections:
```md
## Installation

\```bash
uv add <package>
\```

## Development

\```bash
uv sync --group=development
uv run pre-commit install --install-hooks
uv run pre-commit install --hook-type=commit-msg
\```

## Testing

\```bash
uv sync --group=testing
uv run pytest
\```
```

**workflow.yml**
- [x] Remove `cache-dependency-glob` entry
- [x] Bump uv to `0.5.6`
- [x] Replace `Install requirements` step with `Install the project`:
```
      - name: Install the project
        run: uv sync --group=testing
```
- [x] Replace `run: pytest` with `run: uv run pytest`

**pyproject.toml**
- [x] Add `project` entry at the top with the following keys: `name`,  `version`, `description`,  `readme = "README.md"`, `authors`, `maintainers`,  `requires-python>=3.12`
```toml
[project]
name = "..."
version = "..."
description = "..."
readme = "README.md"
authors = [
    { name = "Stefano Fusai", email = "stefanofusai@gmail.com" }
]
maintainers = [
    { name = "Stefano Fusai", email = "stefanofusai@gmail.com" }
]
requires-python = ">=3.12"
```
- [x] Move `build-system` section after `project.urls`. Change it to:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
``` 
- [x] Bump minor version (`x.1.y` -> `x.2.0`)
- [x] Run `uv add --requirements=.requirements/base.in` / `uv add --requirements=requirements.in`
- [x] Add `dependency-groups` entry after `project.urls`. Order the `development` / `testing` keys, if present, alphabetically after running `uv add`.
- [x] Run `uv add --group=development --requirements=.requirements/development.in` / `uv add --group=testing --requirements=.requirements/testing.in`
- [x] Add `tool.uv` section (ordered alphabetically, likely at the bottom before `tool.uv.sources`) with `default-groups = []`
- [x] Make sure that `project.dependencies`, `dependency-groups` and `dependency-groups`' dependencies are alphabetically sorted
- [x] Manually pin `project.dependencies` versions (replace `>=` with `==`)

**misc**
- [x] Delete `.requirements` folder / `requirements.in` / `requirements.txt` files
