### ISSUE TITLE
Move development dependencies to `dependency-groups`

### ISSUE THREAD

**Issue by stefanofusai** [stefanofusai/drf-multi-serializers#51]
```toml
[dependency-groups]
development = [
    "pre-commit==4.0.1",
    "ruff==0.8.2",
]
```
